project_id = "axsnwyyraybgczmsntur"

[functions.generate-questions-batch]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.validate-questions]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.store-legal-text]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = false

[functions.create-mp-checkout]
verify_jwt = false

[functions.verify-mp-payment]
verify_jwt = false
