project_id = "axsnwyyraybgczmsntur"

[functions.generate-questions-batch]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.store-legal-text]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = false

[functions.create-mp-checkout]
verify_jwt = false

[functions.verify-mp-payment]
verify_jwt = false

[functions.reactivate-access]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-mp-pix-boleto]
verify_jwt = false

[functions.block-expired-access]
verify_jwt = false

[functions.subscription-details]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.apply-audit-patch]
verify_jwt = false

[functions.simulado-semanal]
verify_jwt = false

