
-- Table for user question reports
CREATE TABLE public.question_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  questao_id bigint NOT NULL REFERENCES public.questoes(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  motivo text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pendente',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  admin_notes text
);

ALTER TABLE public.question_reports ENABLE ROW LEVEL SECURITY;

-- Users can insert their own reports
CREATE POLICY "Users can insert own reports"
ON public.question_reports
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Users can read their own reports
CREATE POLICY "Users can read own reports"
ON public.question_reports
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Admins can read all reports
CREATE POLICY "Admins can read all reports"
ON public.question_reports
FOR SELECT
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role));

-- Admins can update reports (resolve, add notes)
CREATE POLICY "Admins can update reports"
ON public.question_reports
FOR UPDATE
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role));

-- Admins can delete reports
CREATE POLICY "Admins can delete reports"
ON public.question_reports
FOR DELETE
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role));
