// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axsnwyyraybgczmsntur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4c253eXlyYXliZ2N6bXNudHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzcyMzAsImV4cCI6MjA4ODA1MzIzMH0.7M7K-g_aGYvnUJZQfXtLhtzP5fQZiPPblURo9cBfm68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});